app/urls.py
from django.urls import path

from app import views

app_name = "app"

urlpatterns = [
    # トップページ
    path("", views.IndexView.as_view(), name="index"),
    # 店舗詳細
    path("store/<int:store_id>/", views.StoreDetailView.as_view(), name="store_detail"),
    path(
        "store/<int:store_id>/<int:service_id>/",
        views.StoreDetailView.as_view(),
        name="store_detail",
    ),
    # 店舗登録
    path("store_register/", views.StoreRegisterView.as_view(), name="store_register"),
    # サービス登録
    path(
        "service_register/",
        views.ServiceRegisterView.as_view(),
        name="service_register",
    ),
    # 店舗特別休日
    path("store_holiday/", views.StoreHolidayView.as_view(), name="store_holiday"),
    # プロフィール
    path("profile/", views.ProfileView.as_view(), name="profile"),
    # 予約
    path("reservation/", views.ReservationView.as_view(), name="reservation"),
    # スタッフ休日
    path("staff_holiday/", views.StaffHolidayView.as_view(), name="staff_holiday"),
]

line/urls.py
from django.urls import path

from line import views

app_name = "line"

urlpatterns = [
    # 店舗一覧
    path("", views.IndexView.as_view(), name="index"),
    # LINEコールバック
    path("callback/", views.CallbackView.as_view(), name="callback"),
    # サービス一覧
    path("service/<int:store_id>/", views.ServiceView.as_view(), name="service"),
    # スタッフ一覧
    path("staff/<int:service_id>/", views.StaffView.as_view(), name="staff"),
    # 予約カレンダー
    path(
        "calendar/<int:service_id>/<int:staff_id>/",
        views.CalendarView.as_view(),
        name="calendar",
    ),
    path(
        "calendar/<int:service_id>/<int:staff_id>/<int:year>/<int:week>/",
        views.CalendarView.as_view(),
        name="calendar",
    ),
    # お客様情報入力
    path(
        "reserve/<int:service_id>/<int:staff_id>/<int:year>/<int:month>/<int:day>/<int:hour>/<int:minute>/",
        views.ReserveView.as_view(),
        name="reserve",
    ),
    # 予約内容確認
    path(
        "confirm/<int:service_id>/<int:staff_id>/<int:year>/<int:month>/<int:day>/<int:hour>/<int:minute>/",
        views.ConfirmView.as_view(),
        name="confirm",
    ),
    # 予約完了
    path("done/", views.DoneView.as_view(), name="done"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # トップページ
    path("", include("app.urls")),
    # アカウント認証
    path("accounts/", include("accounts.urls")),
    # 認証ライブラリ
    path("accounts/", include("allauth.urls")),
    # LINE
    path("line/", include("line.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

line/models.py
from django.db import models

# Create your models here.

line/forms.py
from django import forms

from app.models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ["name", "gender", "phone_number"]
        widgets = {
            "gender": forms.Select(choices=Customer.GENDER_CHOICES),
        }

line/views.py
from datetime import datetime, timedelta

from django.conf import settings
from django.http.response import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseServerError,
)
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View

from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError, LineBotApiError
from linebot.models import (
    FollowEvent,
    MessageEvent,
    PostbackEvent,
    TextMessage,
    UnfollowEvent,
)

from app.models import (
    Customer,
    Reservation,
    Service,
    Staff,
    StaffHoliday,
    Store,
    StoreHoliday,
)
from line.forms import CustomerForm
from line.line_messages import (
    send_reservation_confirm_message,
    send_menu_message,
    send_new_menu_message,
    send_check_reservation_message,
    send_check_reservation_detail_message,
    send_change_reservation_message,
    send_cancel_reservation_message,
)

line_bot_api = LineBotApi(settings.CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(settings.CHANNEL_SECRET)


# テキストメッセージ送信
def send_text_message(line_id, message):
    liff_json = {"type": "text", "text": message}
    result = TextMessage.new_from_json_dict(liff_json)
    try:
        line_bot_api.push_message(line_id, messages=result)
    except Exception:
        print("テキストメッセージを送信できませんでした")


# LINEコールバック
class CallbackView(View):
    def get(self, request):
        return HttpResponse("OK")

    def post(self, request):
        signature = request.META["HTTP_X_LINE_SIGNATURE"]
        body = request.body.decode("utf-8")

        try:
            handler.handle(body, signature)
        except InvalidSignatureError:
            return HttpResponseBadRequest()
        except LineBotApiError as e:
            print(e)
            return HttpResponseServerError()

        return HttpResponse("OK")

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(CallbackView, self).dispatch(*args, **kwargs)

    # 友達追加
    @handler.add(FollowEvent)
    def handle_follow(event):
        line_id = event.source.user_id

        # 既存のユーザーをチェック
        if not Customer.objects.filter(line_id=line_id).exists():
            try:
                # LINEユーザー情報を取得
                profile = line_bot_api.get_profile(line_id)
                # LINEユーザー名
                name = profile.display_name

                # 顧客登録
                Customer.objects.create(name=name, line_id=line_id)
                print("新しい友達追加: ", name)
            except LineBotApiError as e:
                print("新しい友達追加エラー: ", e)
        else:
            print("ユーザーはすでに登録されています。")

    # 友達解除
    @handler.add(UnfollowEvent)
    def handle_unfollow(event):
        line_id = event.source.user_id
        # 対応する顧客を見つけて削除
        try:
            user = Customer.objects.get(line_id=line_id)
            user.delete()
            print("友達解除されたユーザーを削除しました: ", line_id)
        except Customer.DoesNotExist:
            print("削除するユーザーが見つかりませんでした。", line_id)

    # テキストメッセージ
    @handler.add(MessageEvent, message=TextMessage)
    def text_message(event):
        try:
            # LINE ID取得
            line_id = event.source.user_id
            # 顧客情報取得
            customer = Customer.objects.get(line_id=line_id)
            # 予約情報取得
            reservations = Reservation.objects.filter(
                customer=customer, reservation_date__gt=timezone.now()
            )

            # メッセージ判定
            if event.message.text == "予約メニュー":
                if reservations.exists():
                    # 予約メニュー送信(予約あり)
                    send_menu_message(line_id)
                else:
                    # 予約メニュー送信(新規)
                    send_new_menu_message(line_id)
            elif event.message.text == "予約確認":
                if not reservations.exists():
                    send_text_message(line_id, "予約がありません")
                    return

                # 予約確認メッセージ送信
                send_check_reservation_message(line_id, reservations)

            elif event.message.text == "予約変更":
                if not reservations.exists():
                    send_text_message(line_id, "予約がありません")
                    return

                # 予約変更メッセージ送信
                send_change_reservation_message(line_id, reservations)

            elif event.message.text == "予約キャンセル":
                if not reservations.exists():
                    send_text_message(line_id, "予約がありません")
                    return

                # 予約キャンセルメッセージ送信
                send_cancel_reservation_message(line_id, reservations)

        except Exception as e:
            print(e)

    # ポストバック
    @handler.add(PostbackEvent)
    def on_postback(event):
        line_id = event.source.user_id
        data = dict(x.split("=") for x in event.postback.data.split("&"))
        # アクション取得
        action = data["action"]
        # 予約ID取得
        reservation_id = data["reservation_id"]
        reservation = Reservation.objects.get(id=reservation_id)

        if action == "予約確認":
            # 予約詳細メッセージ送信
            send_check_reservation_detail_message(line_id, reservation)

        elif action == "予約キャンセル":
            reservation.delete()
            send_text_message(line_id, "予約をキャンセルしました")


# 店舗一覧
class IndexView(View):
    def get(self, request):
        stores = (
            Store.objects.filter(services__staff__isnull=False)
            .distinct()
            .order_by("-created_at")
        )
        reservation_id = request.GET.get("reservation_id", None)

        return render(
            request,
            "line/index.html",
            {
                "stores": stores,
                "reservation_id": reservation_id,
                "liff_id": settings.LIFF_ID,
            },
        )


# LINE IDチェック
def check_line_id(request):
    line_id = request.GET.get("line_id")

    if line_id:
        return line_id
    else:
        redirect("line:index")


# サービス一覧
class ServiceView(View):
    def get(self, request, store_id):
        store = Store.objects.get(id=store_id)
        services = Service.objects.filter(store=store).order_by("-created_at")
        reservation_id = request.GET.get("reservation_id", None)
        line_id = check_line_id(request)

        return render(
            request,
            "line/service.html",
            {
                "services": services,
                "reservation_id": reservation_id,
                "line_id": line_id,
            },
        )


# スタッフ一覧
class StaffView(View):
    def get(self, request, service_id):
        staffs = Staff.objects.filter(services__id=service_id)
        reservation_id = request.GET.get("reservation_id", None)
        line_id = check_line_id(request)

        return render(
            request,
            "line/staff.html",
            {
                "staffs": staffs,
                "service_id": service_id,
                "reservation_id": reservation_id,
                "line_id": line_id,
            },
        )


# 予約不可日を取得
def get_disabled_dates(year, store, staff_id, week_dates):
    # 店舗の特別休日を取得
    store_holidays = StoreHoliday.objects.filter(holiday__year=year).values_list(
        "holiday", flat=True
    )

    store_holidays = [h.strftime("%Y-%m-%d") for h in store_holidays]

    # スタッフの休暇を取得
    staff_holidays = StaffHoliday.objects.filter(
        holiday__year=year, staff_id=staff_id
    ).values_list("holiday", flat=True)

    staff_holidays = [h.strftime("%Y-%m-%d") for h in staff_holidays]

    # 休日を取得
    day_mapping = {
        0: "closed_monday",
        1: "closed_tuesday",
        2: "closed_wednesday",
        3: "closed_thursday",
        4: "closed_friday",
        5: "closed_saturday",
        6: "closed_sunday",
    }

    weekday_holidays = set()
    for week_date in week_dates:
        day_of_week = week_date.weekday()
        if getattr(store, day_mapping[day_of_week]):
            weekday_holidays.add(week_date.strftime("%Y-%m-%d"))

    # 過去は予約不可
    today = datetime.now().date()
    past_dates = {
        week_date.strftime("%Y-%m-%d") for week_date in week_dates if week_date <= today
    }

    # 結合して、重複を削除
    disabled_dates = set(store_holidays).union(
        staff_holidays, weekday_holidays, past_dates
    )
    return disabled_dates


def get_week_dates(date):
    start_of_week = date - timedelta(days=date.weekday())
    return [start_of_week.date() + timedelta(days=i) for i in range(7)]


# 予約カレンダー
class CalendarView(View):
    def get(self, request, service_id, staff_id, year=None, week=None):
        reservation_id = request.GET.get("reservation_id", None)
        line_id = check_line_id(request)

        today = datetime.today()

        # 年と週を取得
        if year is None:
            year = today.year
        if week is None:
            week = today.isocalendar()[1]

        # サービス取得
        service = Service.objects.get(id=service_id)
        # スタッフ取得
        staff = Staff.objects.get(id=staff_id)

        first_day_of_year = datetime(year, 1, 1)
        if first_day_of_year.weekday() > 0:
            first_day_of_year -= timedelta(days=first_day_of_year.weekday())

        # 週の日付を取得
        current_date = first_day_of_year + timedelta(weeks=week - 1)
        week_dates = get_week_dates(current_date)

        # 営業時間を取得
        opening_time = service.store.open_time.hour
        closing_time = service.store.close_time.hour
        # 予約間隔
        interval = 30

        # 時間スロットを取得
        time_slots = [
            datetime(year, 1, 1, hour=h, minute=m).time()
            for h in range(opening_time, closing_time)
            for m in (0, interval)
        ]

        # 予約不可日を取得
        disabled_dates = get_disabled_dates(year, service.store, staff_id, week_dates)

        # 予約状況を取得
        availability = {}

line/templates/line/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.min.css' %}"
    />
    <title>予約システム</title>
  </head>

  <body>
    <main class="container mx-auto max-w-screen-sm px-2 py-5">
      {% block content %} {% endblock %}
    </main>

    <script
      charset="utf-8"
      src="https://static.line-scdn.net/liff/edge/2/sdk.js"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    {% block extrajs %} {% endblock %}
  </body>
</html>

line/templates/line/calendar.html
{% extends "line/base.html" %} {% load static %} {% load custom_filter %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">予約カレンダー</div>

<div>
  <div class="flex items-center justify-between mb-2">
    <a
      href="{% url 'line:calendar' service_id=service_id staff_id=staff.id year=current_year week=current_week|add:'-1' %}{% if reservation_id %}?reservation_id={{ reservation_id }}{% endif %}{% if reservation_id %}&{% else %}?{% endif %}line_id={{line_id}}"
    >
      <div class="border rounded-full px-3 py-1 shadow">前の週へ</div>
    </a>
    <a
      href="{% url 'line:calendar' service_id=service_id staff_id=staff.id year=current_year week=current_week|add:'1' %}{% if reservation_id %}?reservation_id={{ reservation_id }}{% endif %}{% if reservation_id %}&{% else %}?{% endif %}line_id={{line_id}}"
    >
      <div class="border rounded-full px-3 py-1 shadow">次の週へ</div>
    </a>
  </div>

  <div class="text-center text-white bg-black py-2">
    {{current_year}}年{{current_month}}月
  </div>

  <table class="text-center w-full border">
    <thead>
      <tr class="border-b text-sm">
        <th class="border-r p-1">日時</th>
        {% for date in week_dates %}
        <th
          class="border-r p-1 {% if date.weekday == 5 %}text-blue-500{% elif date.weekday == 6 %}text-red-500{% endif %}"
        >
          {{ date|date:"d" }} {{ date|date:"(D)" }}
        </th>
        {% endfor %}
      </tr>
    </thead>

    <tbody>
      {% for time_slot in time_slots %}
      <tr class="border-b text-sm">
        <td class="border-r p-1">{{ time_slot|time:"H:i" }}</td>
        {% for date in week_dates %}
        <td class="border-r">
          {% with availability|get_date_availability:date|get_time_slot_availability:time_slot as slot_available %}
            {% if slot_available %}
              <div class="bg-gray-400 p-1 flex items-center justify-center">
                <img src="{% static 'img/cross.svg' %}" alt="" class="w-6 h-6" />
              </div>
            {% else %}
              <a
                href="{% url 'line:reserve' service_id=service_id staff_id=staff.id year=current_year month=date|date:'m' day=date|date:'d' hour=time_slot|time:'H' minute=time_slot|time:'i' %}{% if reservation_id %}?reservation_id={{ reservation_id }}{% endif %}{% if reservation_id %}&{% else %}?{% endif %}line_id={{line_id}}"
              >
                <div class="p-1 flex items-center justify-center">
                  <img src="{% static 'img/circle.svg' %}" alt="" class="w-6 h-6" />
                </div>
              </a>
            {% endif %}
          {% endwith %}
        </td>
        {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

line/templates/line/confirm.html
{% extends "line/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">予約内容確認</div>

<div class="font-bold mb-2">メニュー</div>
<div class="mb-5">{{ service.name }}</div>

<div class="font-bold mb-2">指名スタッフ</div>
<div class="mb-5">{{ staff.user.name }}</div>

<div class="font-bold mb-2">予約日時</div>
<div class="mb-5">{{ reservation_date }}</div>

<form method="post" action="">
  {% csrf_token %}
  <div class="text-center">
    <button class="bg-black text-white font-bold w-full rounded py-2" type="submit">予約を確定する</button>
  </div>
</form>

{% endblock %}

line/templates/line/done.html
{% extends "line/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">予約完了</div>

<div class="text-center">
  <div>予約が完了しました。</div>
  <div>ブラウザを閉じてください。</div>
</div>
{% endblock %}

line/templates/line/index.html
{% extends "line/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">店舗一覧</div>

{% if stores %}
<div>
  {% for store in stores %}
  <div class="border mb-5 w-full rounded-md">
    <a
      class="store-link"
      href="{% url 'line:service' store.id %}{% if reservation_id %}?reservation_id={{ reservation_id }}{% endif %}"
    >
      <div class="relative pb-[56.25%] overflow-hidden rounded-t-md">
        {% if store.image %}
        <img
          src="{{store.image.url}}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% else %}
        <img
          src="{% static 'img/noImage.png' %}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% endif %}
      </div>

      <div class="p-2 space-y-1">
        <div class="font-bold">{{ store.name }}</div>
        <div>住所：{{ store.address }}</div>
        <div>電話番号：{{ store.tel }}</div>
        <div>営業時間：{{ store.open_time }}～{{ store.close_time }}</div>
        <div>定休日：{{ store.get_closed_days }}</div>
        <div class="whitespace-pre-line">{{ store.description }}</div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="text-center">担当スタッフがいる店舗が登録されていません。</div>
{% endif %} {% endblock %} {% block extrajs %}

<script>
  $(function () {
    liff.init({ liffId: "{{ liff_id }}" }).then(() => {
      if (!liff.isLoggedIn()) {
        liff.login()
      } else {
        liff.getProfile().then((profile) => {
          const line_id = profile.userId
          const links = document.querySelectorAll("a.store-link")
          links.forEach((link) => {
            let href = link.href
            href += (href.indexOf("?") !== -1 ? "&" : "?") + "line_id=" + line_id
            link.href = href
          })
        })
      }
    })
  })
</script>
{% endblock %}

line/templates/line/reserve.html
{% extends "line/base.html" %} {% load widget_tweaks %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">お客様情報入力</div>

<div>
  <form method="post">
    {% csrf_token %}
    <div class="font-bold mb-2">名前</div>
    <div class="mb-5">
      {% render_field form.name class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="名前" %}
    </div>

    <div class="font-bold mb-2">性別</div>
    <div class="mb-5">
      {% render_field form.gender class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="font-bold mb-2">電話番号</div>
    <div class="mb-5">
      {% render_field form.phone_number class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="text-center">
      <button class="bg-black text-white font-bold w-full rounded py-2" type="submit">予約内容を確認する</button>
    </div>
  </form>
</div>
{% endblock %}

line/templates/line/service.html
{% extends "line/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">サービス一覧</div>

<div>
  {% for service in services %}
  <div class="border mb-5 w-full rounded-md">
    <a
      href="{% url 'line:staff' service.id %}{% if reservation_id %}?reservation_id={{ reservation_id }}{% endif %}{% if reservation_id %}&{% else %}?{% endif %}line_id={{line_id}}"
    >
      <div class="relative pb-[56.25%] overflow-hidden rounded-t-md">
        {% if service.image %}
        <img
          src="{{service.image.url}}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% else %}
        <img
          src="{% static 'img/noImage.png' %}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% endif %}
      </div>

      <div class="p-2 space-y-1">
        <div class="font-bold">{{ service.name }}</div>
        <div>料金：{{ service.price }}円</div>
        <div>所要時間：{{ service.duration }}時間</div>
        <div class="whitespace-pre-line">{{ service.description }}</div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}

line/templates/line/staff.html
{% extends "line/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">スタッフ</div>

<div class="grid grid-cols-2 gap-2">
  {% for staff in staffs %}
  <div class="border mb-5 w-full rounded-md">
    <a
      href="{% url 'line:calendar' service_id=service_id staff_id=staff.id %}{% if reservation_id %}?reservation_id={{ reservation_id }}{% endif %}{% if reservation_id %}&{% else %}?{% endif %}line_id={{line_id}}"
    >
      <div class="relative pb-[177.77%] overflow-hidden rounded-t-md">
        {% if staff.image %}
        <img
          src="{{staff.image.url}}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% else %}
        <img
          src="{% static 'img/noImage.png' %}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% endif %}
      </div>

      <div class="p-2 space-y-1">
        <div class="font-bold">{{ staff.user.name }}</div>
        <div>{{ staff.position }}</div>
        <div>指名料：{{ staff.nomination_fee }}円</div>
        <div class="whitespace-pre-line">{{ staff.bio }}</div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
{% endblock %}