accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    # ログイン
    path("login/", views.LoginView.as_view(), name="login"),
    # ログアウト
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # アカウント登録
    path('signup/', views.SignupView.as_view(), name='signup'),
]

app/urls.py
from django.urls import path

from app import views

app_name = "app"

urlpatterns = [
    # トップページ
    path("", views.IndexView.as_view(), name="index"),
    # 店舗詳細
    path("store/<int:store_id>/", views.StoreDetailView.as_view(), name="store_detail"),
    path(
        "store/<int:store_id>/<int:service_id>/",
        views.StoreDetailView.as_view(),
        name="store_detail",
    ),
    # 店舗登録
    path("store_register/", views.StoreRegisterView.as_view(), name="store_register"),
    # サービス登録
    path(
        "service_register/",
        views.ServiceRegisterView.as_view(),
        name="service_register",
    ),
    # 店舗特別休日
    path("store_holiday/", views.StoreHolidayView.as_view(), name="store_holiday"),
    # プロフィール
    path("profile/", views.ProfileView.as_view(), name="profile"),
    # 予約
    path("reservation/", views.ReservationView.as_view(), name="reservation"),
    # スタッフ休日
    path("staff_holiday/", views.StaffHolidayView.as_view(), name="staff_holiday"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # トップページ
    path("", include("app.urls")),
    # アカウント認証
    path("accounts/", include("accounts.urls")),
    # 認証ライブラリ
    path("accounts/", include("allauth.urls")),
    # LINE
    path("line/", include("line.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

from accounts.models import UserAccount


# 店舗
class Store(models.Model):
    name = models.CharField(verbose_name="店舗名", max_length=100)
    address = models.CharField(
        verbose_name="住所", max_length=100, null=True, blank=True
    )
    tel = models.CharField(
        verbose_name="電話番号", max_length=100, null=True, blank=True
    )
    description = models.TextField(verbose_name="詳細", null=True, blank=True)
    image = models.ImageField(
        upload_to="reservation/store", verbose_name="画像", null=True, blank=True
    )
    open_time = models.TimeField(verbose_name="開店時間", default="09:00:00")
    close_time = models.TimeField(verbose_name="閉店時間", default="21:00:00")

    closed_monday = models.BooleanField(verbose_name="月曜定休", default=False)
    closed_tuesday = models.BooleanField(verbose_name="火曜定休", default=False)
    closed_wednesday = models.BooleanField(verbose_name="水曜定休", default=False)
    closed_thursday = models.BooleanField(verbose_name="木曜定休", default=False)
    closed_friday = models.BooleanField(verbose_name="金曜定休", default=False)
    closed_saturday = models.BooleanField(verbose_name="土曜定休", default=False)
    closed_sunday = models.BooleanField(verbose_name="日曜定休", default=False)

    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    def get_closed_days(self):
        days = []
        if self.closed_monday:
            days.append("月曜")
        if self.closed_tuesday:
            days.append("火曜")
        if self.closed_wednesday:
            days.append("水曜")
        if self.closed_thursday:
            days.append("木曜")
        if self.closed_friday:
            days.append("金曜")
        if self.closed_saturday:
            days.append("土曜")
        if self.closed_sunday:
            days.append("日曜")
        return ", ".join(days) if days else "なし"

    class Meta:
        verbose_name = "店舗"
        verbose_name_plural = "店舗"

    def __str__(self):
        return self.name


# サービス
class Service(models.Model):
    store = models.ForeignKey(
        Store, on_delete=models.CASCADE, verbose_name="店舗", related_name="services"
    )
    name = models.CharField(max_length=255, verbose_name="名前")
    duration = models.FloatField(verbose_name="所要時間")
    price = models.IntegerField(verbose_name="料金")
    description = models.TextField(verbose_name="詳細")
    image = models.ImageField(
        upload_to="reservation/service", verbose_name="画像", blank=True, null=True
    )

    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    class Meta:
        verbose_name = "サービス"
        verbose_name_plural = "サービス"

    def __str__(self):
        return self.name


# スタッフ
class Staff(models.Model):
    user = models.OneToOneField(
        UserAccount,
        on_delete=models.CASCADE,
        related_name="staff_profile",
        verbose_name="アカウント",
    )
    services = models.ManyToManyField(
        Service, verbose_name="サービス", related_name="staff"
    )
    position = models.CharField(max_length=100, verbose_name="職位", default="未設定")
    nomination_fee = models.IntegerField(verbose_name="指名料", default=0)
    bio = models.TextField(verbose_name="自己紹介", blank=True, null=True)
    image = models.ImageField(
        upload_to="reservation/staff", verbose_name="画像", blank=True, null=True
    )

    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    class Meta:
        verbose_name = "スタッフ"
        verbose_name_plural = "スタッフ"

    def __str__(self):
        return self.user.name


# 顧客
class Customer(models.Model):
    GENDER_CHOICES = (
        ("male", "男性"),
        ("female", "女性"),
        ("other", "その他"),
    )

    name = models.CharField(max_length=255, verbose_name="名前")
    gender = models.CharField(
        max_length=10,
        verbose_name="性別",
        choices=GENDER_CHOICES,
        blank=True,
        null=True,
    )
    phone_number = models.CharField(
        max_length=15, verbose_name="電話番号", blank=True, null=True
    )
    line_id = models.CharField(max_length=255, unique=True, verbose_name="LINE ID")

    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    class Meta:
        verbose_name = "顧客"
        verbose_name_plural = "顧客"

    def __str__(self):
        return self.name


# 予約
class Reservation(models.Model):
    service = models.ForeignKey(
        Service, verbose_name="サービス", on_delete=models.CASCADE
    )
    staff = models.ForeignKey(Staff, verbose_name="スタッフ", on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Customer, verbose_name="お客様情報", on_delete=models.CASCADE
    )
    reservation_date = models.DateTimeField(verbose_name="予約日時")

    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    class Meta:
        verbose_name = "予約"
        verbose_name_plural = "予約"

    def __str__(self):
        return f"{self.reservation_date.strftime('%Y-%m-%d %H:%M')} - {self.customer.name} - {self.service.name} by {self.staff.user.name if self.staff else '指定なし'}"


# 店舗特別休日
class StoreHoliday(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, verbose_name="店舗")
    holiday = models.DateField(verbose_name="休業日")
    reason = models.CharField(max_length=255, verbose_name="理由", blank=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    class Meta:
        verbose_name = "店舗休業日"
        verbose_name_plural = "店舗休業日"

    def __str__(self):
        return f"{self.holiday} - {self.reason}"


# スタッフ休日
class StaffHoliday(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, verbose_name="スタッフ")
    holiday = models.DateField(verbose_name="休日")
    reason = models.CharField(max_length=255, verbose_name="理由", blank=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    class Meta:
        verbose_name = "スタッフ休日"
        verbose_name_plural = "スタッフ休日"

    def __str__(self):
        return f"{self.staff.user.name} - {self.holiday} - {self.reason}"

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.min.css' %}"
    />

    <title>予約システム</title>
  </head>

  <body class="flex flex-col min-h-screen">
    <nav class="py-2 border-b">
      <div
        class="max-w-screen-sm flex justify-between items-center mx-auto px-2"
      >
        <div class="text-xl font-bold">
          <a href="/">予約システム</a>
        </div>

        <div class="flex items-center space-x-5 text-sm">
          {% if user.is_authenticated %}
          <!-- ログイン状態 -->
          {% if user.is_superuser %}
          <!-- 管理者 -->
          <a href="{% url 'app:store_register' %}">店舗登録</a>
          <a href="{% url 'app:service_register' %}" class="">サービス登録</a>
          <a href="{% url 'app:store_holiday' %}" class="">特別休日登録</a>
          {% else %}
          <!-- スタッフ -->
          <a href="{% url 'app:profile' %}" class="">プロフィール</a>
          <a href="{% url 'app:reservation' %}" class="">予約一覧</a>
          <a href="{% url 'app:staff_holiday' %}" class="">休日登録</a>
          {% endif %}
          <a href="{% url 'accounts:logout' %}">ログアウト</a>
          {% else %}
          <!-- ログアウト状態 -->
          <a href="{% url 'accounts:login' %}">ログイン</a>
          <a href="{% url 'accounts:signup' %}">アカウント登録</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <main class="flex-1 container mx-auto max-w-screen-sm px-2 py-5">
      {% block content %} {% endblock %}
    </main>

    <footer class="border-t py-2 text-center text-sm mt-5">
      &copy; フルスタックチャンネル
    </footer>
  </body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">店舗一覧</div>

<div class="grid grid-cols-2 gap-5">
  {% for store in stores %}
  <div class="border rounded-md">
    <a href="{% url 'app:store_detail' store.id %}">
      <div class="relative pb-[56.25%] overflow-hidden rounded-t-md">
        {% if store.image %}
        <img
          src="{{store.image.url}}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% else %}
        <img
          src="{% static 'img/noImage.png' %}"
          alt="画像"
          class="absolute top-0 left-0 w-full h-full object-cover"
        />
        {% endif %}
      </div>
    </a>

    <div class="p-2">
      <div class="font-bold">{{ store.name }}</div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

app/templates/app/profile.html
{% extends "app/base.html" %} {% load widget_tweaks %}  {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">プロフィール</div>

<div class="mb-5">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="font-bold mb-2">名前</div>
    <div class="mb-5">
      {% render_field form.name class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="名前" %}
    </div>

    <div class="font-bold mb-2">プロフィール画像</div>
    <div class="mb-5">
      {{ form.image }}
    </div>

    <div class="font-bold mb-2">職位</div>
    <div class="mb-5">
      {% render_field form.position class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="スタイリスト" %}
    </div>

    <div class="font-bold mb-2">指名料</div>
    <div class="mb-5">
      {% render_field form.nomination_fee class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="font-bold mb-2">自己紹介</div>
    <div class="mb-5">
      {% render_field form.bio class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="text-center">
      <button class="bg-black text-white font-bold w-full rounded py-2" type="submit">登録する</button>
    </div>
  </form>
</div>

{% endblock %}

app/templates/app/reservation.html
{% extends "app/base.html" %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">予約一覧</div>

<table class="w-full text-center border rounded">
  <tr class="bg-gray-100 border-b">
    <th class="py-2 border-r">日時</th>
    <th class="py-2 border-r">サービス</th>
    <th class="py-2 border-r">名前</th>
    <th class="py-2 border-r">性別</th>
    <th class="py-2 border-r">電話番号</th>
    <th class="py-2">担当者</th>
  </tr>
  {% for reservation in reservations %}
  <tr class="border-b">
    <td class="py-2 border-r">{{ reservation.reservation_date }}</td>
    <td class="py-2 border-r">{{ reservation.service.name }}</td>
    <td class="py-2 border-r">{{ reservation.customer.name }}</td>
    <td class="py-2 border-r">{{ reservation.customer.get_gender_display }}</td>
    <td class="py-2 border-r">{{ reservation.customer.phone_number }}</td>
    <td class="py-2">{{ reservation.staff.user.name }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

app/templates/app/service_register.html
{% extends "app/base.html" %} {% load widget_tweaks %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">サービス登録</div>

<div class="mb-5">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="font-bold mb-2">店舗</div>
    <div class="mb-5">
      {% render_field form.store class="border w-full p-2 rounded bg-gray-50 focus:bg-white" %}
    </div>

    <div class="font-bold mb-2">サービス名</div>
    <div class="mb-5">
      {% render_field form.name class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="サービス名" %}
    </div>

    <div class="font-bold mb-2">画像</div>
    <div class="mb-5">{{ form.image }}</div>

    <div class="font-bold mb-2">所要時間</div>
    <div class="mb-5">
      {% render_field form.duration class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="1" %}
    </div>

    <div class="font-bold mb-2">料金</div>
    <div class="mb-5">
      {% render_field form.price class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="2000"%}
    </div>

    <div class="font-bold mb-2">説明</div>
    <div class="mb-5">
      {% render_field form.description class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="text-center">
      <button
        class="bg-black text-white font-bold w-full rounded py-2"
        type="submit"
      >
        登録する
      </button>
    </div>
  </form>
</div>

{% endblock %}

app/templates/app/staff_holiday.html
{% extends "app/base.html" %} {% load widget_tweaks %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">休日登録</div>

<form method="post" class="mb-5">
  {% csrf_token %}
  <div>
    <div class="font-bold mb-2">休日</div>
    <div class="mb-5">
      {% render_field form.holiday class="border w-full p-2 rounded bg-gray-50 focus:bg-white" %}
    </div>
    <div class="font-bold mb-2">理由</div>
    <div class="mb-5">
      {% render_field form.reason class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="理由" %}
    </div>
  </div>

  <div class="text-center">
    <button
      class="bg-black text-white font-bold w-full rounded py-2"
      type="submit"
    >
      登録する
    </button>
  </div>
</form>

<div class="text-center font-bold text-2xl mb-5">登録済みの休日</div>

<table class="w-full text-center border rounded">
  <tr class="bg-gray-100 border-b">
    <th class="py-2 border-r">休日</th>
    <th class="py-2">理由</th>
  </tr>
  {% for staff_holiday in staff_holidays %}
  <tr class="border-b">
    <td class="py-2 border-r w-[150px]">{{ staff_holiday.holiday }}</td>
    <td class="py-2">{{ staff_holiday.reason }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

app/templates/app/store_detail.html
{% extends "app/base.html" %} {% load static %} {% load custom_filter %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">{{ store.name }}</div>

<div class="mb-5">
  <div class="relative pb-[56.25%] overflow-hidden rounded-t-md">
    {% if store.image %}
    <img
      src="{{store.image.url}}"
      alt="画像"
      class="absolute top-0 left-0 w-full h-full object-cover"
    />
    {% else %}
    <img
      src="{% static 'img/noImage.png' %}"
      alt="画像"
      class="absolute top-0 left-0 w-full h-full object-cover"
    />
    {% endif %}
  </div>

  <div class="p-2 space-y-1">
    <div>住所：{{ store.address }}</div>
    <div>電話番号：{{ store.tel }}</div>
    <div>営業時間：{{ store.open_time }}～{{ store.close_time }}</div>
    <div>定休日：{{ store.get_closed_days }}</div>
    <div class="whitespace-pre-line">{{ store.description }}</div>
  </div>
</div>

<div class="text-center font-bold text-2xl mb-5">サービス一覧</div>

<div class="grid grid-cols-2 gap-5">
  {% for service in services %}
  <div class="border rounded-md flex flex-col">
    <div class="relative pb-[56.25%] overflow-hidden rounded-t-md">
      {% if service.image %}
      <img
        src="{{service.image.url}}"
        alt="画像"
        class="absolute top-0 left-0 w-full h-full object-cover"
      />
      {% else %}
      <img
        src="{% static 'img/noImage.png' %}"
        alt="画像"
        class="absolute top-0 left-0 w-full h-full object-cover"
      />
      {% endif %}
    </div>

    <div class="p-2 space-y-1 flex flex-col flex-1">
      <div class="mb-5 flex-1">
        <div class="font-bold">{{ service.name }}</div>
        <div>所要時間：{{ service.duration }}時間</div>
        <div>料金：{{ service.price }}円</div>
        <div class="whitespace-pre-line">{{ service.description }}</div>
      </div>

      {% if has_staff_profile %}
      <form
        action="{% url 'app:store_detail' store.id service.id %}"
        method="post"
      >
        {% csrf_token %} {% if services_status|get_item:service.id %}
        <input type="hidden" name="action" value="remove" />
        <button
          class="bg-red-500 py-2 rounded text-white w-full text-sm"
          type="submit"
        >
          解除する
        </button>
        {% else %}
        <input type="hidden" name="action" value="assign" />
        <button
          class="bg-black py-2 rounded text-white w-full text-sm"
          type="submit"
        >
          担当する
        </button>

        {% endif %}
      </form>
      {% endif %}
    </div>
  </div>
  {% empty %}
  <div class="col-span-2 text-center">サービスが登録されていません</div>
  {% endfor %}
</div>

{% endblock %}

app/templates/app/store_holiday.html
{% extends "app/base.html" %} {% load widget_tweaks %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">特別休日登録</div>

<form method="post" class="mb-5">
  {% csrf_token %}
  <div>
    <div class="font-bold mb-2">店舗</div>
    <div class="mb-5">
      {% render_field form.store class="border w-full p-2 rounded bg-gray-50 focus:bg-white" %}
    </div>

    <div class="font-bold mb-2">休日</div>
    <div class="mb-5">
      {% render_field form.holiday class="border w-full p-2 rounded bg-gray-50 focus:bg-white" %}
    </div>

    <div class="font-bold mb-2">理由</div>
    <div class="mb-5">
      {% render_field form.reason class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="理由" %}
    </div>
  </div>

  <div class="text-center">
    <button
      class="bg-black text-white font-bold w-full rounded py-2"
      type="submit"
    >
      登録する
    </button>
  </div>
</form>

<div class="text-center font-bold text-2xl mb-5">登録済みの休日</div>

<table class="w-full text-center border rounded">
  <tr class="bg-gray-100 border-b">
    <th class="py-2 border-r">店舗</th>
    <th class="py-2 border-r">休業日</th>
    <th class="py-2">理由</th>
  </tr>
  {% for store_holiday in store_holidays %}
  <tr class="border-b">
    <td class="py-2 border-r w-[150px]">{{ store_holiday.store.name }}</td>
    <td class="py-2 border-r w-[150px]">{{ store_holiday.holiday }}</td>
    <td class="py-2">{{ store_holiday.reason }}</td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

app/templates/app/store_register.html
{% extends "app/base.html" %} {% load widget_tweaks %} {% load static %} {% block content %}
<div class="text-center font-bold text-2xl mb-5">店舗登録</div>

<div class="mb-5">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="font-bold mb-2">店舗名</div>
    <div class="mb-5">
      {% render_field form.name class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="店舗名" %}
    </div>

    <div class="font-bold mb-2">店舗画像</div>
    <div class="mb-5">{{ form.image }}</div>

    <div class="font-bold mb-2">開店時間</div>
    <div class="mb-5">
      {% render_field form.open_time class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="font-bold mb-2">閉店時間</div>
    <div class="mb-5">
      {% render_field form.close_time class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="font-bold mb-2">定休日</div>

    <table class="w-full text-center border rounded mb-5">
      <tr class="bg-gray-100 border-b">
        <th class="py-2 border-r">月</th>
        <th class="py-2 border-r">火</th>
        <th class="py-2 border-r">水</th>
        <th class="py-2 border-r">木</th>
        <th class="py-2 border-r">金</th>
        <th class="py-2 border-r text-blue-500">土</th>
        <th class="py-2 text-red-500">日</th>
      </tr>
      <tr class="border-b">
        <td class="py-2 border-r">{% render_field form.closed_monday %}</td>
        <td class="py-2 border-r">{% render_field form.closed_tuesday %}</td>
        <td class="py-2 border-r">{% render_field form.closed_wednesday %}</td>
        <td class="py-2 border-r">{% render_field form.closed_thursday %}</td>
        <td class="py-2 border-r">{% render_field form.closed_friday %}</td>
        <td class="py-2 border-r">{% render_field form.closed_saturday %}</td>
        <td class="py-2">{% render_field form.closed_sunday %}</td>
      </tr>
    </table>

    <div class="font-bold mb-2">住所</div>
    <div class="mb-5">
      {% render_field form.address class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="東京都品川区"%}
    </div>

    <div class="font-bold mb-2">電話番号</div>
    <div class="mb-5">
      {% render_field form.tel class="border w-full p-2 rounded bg-gray-50 focus:bg-white" placeholder="00-0000-0000"%}
    </div>

    <div class="font-bold mb-2">詳細</div>
    <div class="mb-5">
      {% render_field form.description class="border w-full p-2 rounded bg-gray-50 focus:bg-white"%}
    </div>

    <div class="text-center">
      <button
        class="bg-black text-white font-bold w-full rounded py-2"
        type="submit"
      >
        登録する
      </button>
    </div>
  </form>
</div>

{% endblock %}